### PR TITLE
Django 2.2 and tests

### PR DESCRIPTION
**Pull request by rtucker-mozilla**
This PR adds support for python3 and django 2.2.
It also adds tests for quite a lot of the core functionality.

### CODE REVIEW

**Comment by rtucker-mozilla** [comment]
@gene1wood I'm going to test on the dev box soon. Any thoughts/objections here?

Thanks!

**Comment by rtucker-mozilla** [comment]
@gene1wood I'm going to test on the dev box soon. Any thoughts/objections here?

Thanks!

**Comment by gene1wood** [comment]
No prob, I'm not using/haven't been using the dev box

**Comment by rtucker-mozilla** [comment]
Any issues with this code? Me pushing to prod after working with EUS?

**Comment by gene1wood** [comment]
I haven't had a chance to review it yet (in the middle of a work week). Considering the data stored in WDE I agree that we should review it before going to production.

What's the timeline for this needing to get to prod (to know how to resource someone to review this from a security perspective)?

**Comment by rtucker-mozilla** [comment]
No big rush. Over the next month would be great though.

**Comment by rtucker-mozilla** [comment]
@gene1wood Any chance you can look at this soon? I'd like to push it to production the week of 6/10 or 6/17.

Thanks!

**Comment by rtucker-mozilla** [comment]
Went ahead and merged this

**Pull request merged**
